### ISSUE TITLE
-bash: /usr/bin/lsd: No such file or directory

### ISSUE THREAD

**Issue by Alchemist-xD** [TruncatedDinosour/dotfiles-termux#1]
Hi Ari, 
    I tried installing your termux dotfiles.
But after installing, i am getting error "-bash: /usr/bin/lsd: No such file or directory". Can you please guide me to setup this dotfiles in my termux.

**Comment by ar1ja** [comment]
Hi person,
/usr/bin/lsd is a program which just improves ls

If you want to install lsd:

```sh
pkg install lsd
```

Or if you just want to remove the alias, remove it from `~/.config/shells/bash/bash.aliases`

**Comment by Alchemist-xD** [comment]
> Hi person, /usr/bin/lsd is a program which just improves ls
> 
> If you want to install lsd:
> 
> ```shell
> pkg install lsd
> ```
> 
> Or if you just want to remove the alias, remove it from `~/.config/shells/bash/bash.aliases`

Thanks mate,  it worked

One more help if possible. I am getting this error "Error: Error on...quires pyx support on vim. & Server languageserver.ccls failed to start: Launching server "languageserver.ccls" using command ccls failed." while open vim. Plugins are already installed. Do I need to do anything else?

**Comment by ar1ja** [comment]
> > Hi person, /usr/bin/lsd is a program which just improves ls
> > If you want to install lsd:
> > ```shell
> > pkg install lsd
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or if you just want to remove the alias, remove it from `~/.config/shells/bash/bash.aliases`
> 
> Thanks mate, it worked
> 
> One more help if possible. I am getting this error "Error: Error on...quires pyx support on vim. & Server languageserver.ccls failed to start: Launching server "languageserver.ccls" using command ccls failed." while open vim. Plugins are already installed. Do I need to do anything else?

Yeah this is bc default vim binary does not support python, you have to compile vim manually, but I rarely need
vim on my phone or my phone in general so idc rlly, if you want here's a compile script: https://files.ari-web.xyz/files/compile_vim.sh
and install these packages:

```sh
apt update && apt install cargo nodejs npm clang gcc ccls python3 python3-pip ruby tcl \
        xorg-dev lua5.4 liblua5.4-dev binutils perl binutils fasm xclip curl \
        git shfmt clang-format tmux bash-completion man-db mlocate \
        pkgconf  -y
```

If a package fails to install just remove it form the list

**Comment by Alchemist-xD** [comment]
> > > Hi person, /usr/bin/lsd is a program which just improves ls
> > > If you want to install lsd:
> > > ```shell
> > > pkg install lsd
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Or if you just want to remove the alias, remove it from `~/.config/shells/bash/bash.aliases`
> > 
> > 
> > Thanks mate, it worked
> > One more help if possible. I am getting this error "Error: Error on...quires pyx support on vim. & Server languageserver.ccls failed to start: Launching server "languageserver.ccls" using command ccls failed." while open vim. Plugins are already installed. Do I need to do anything else?
> 
> Yeah this is bc default vim binary does not support python, you have to compile vim manually, but I rarely need vim on my phone or my phone in general so idc rlly, if you want here's a compile script: https://files.ari-web.xyz/files/compile_vim.sh and install these packages:
> 
> ```shell
> apt update && apt install cargo nodejs npm clang gcc ccls python3 python3-pip ruby tcl \
>         xorg-dev lua5.4 liblua5.4-dev binutils perl binutils fasm xclip curl \
>         git shfmt clang-format tmux bash-completion man-db mlocate \
>         pkgconf  -y
> ```
> 
> If a package fails to install just remove it form the li

> > > Hi person, /usr/bin/lsd is a program which just improves ls
> > > If you want to install lsd:
> > > ```shell
> > > pkg install lsd
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Or if you just want to remove the alias, remove it from `~/.config/shells/bash/bash.aliases`
> > 
> > 
> > Thanks mate, it worked
> > One more help if possible. I am getting this error "Error: Error on...quires pyx support on vim. & Server languageserver.ccls failed to start: Launching server "languageserver.ccls" using command ccls failed." while open vim. Plugins are already installed. Do I need to do anything else?
> 
> Yeah this is bc default vim binary does not support python, you have to compile vim manually, but I rarely need vim on my phone or my phone in general so idc rlly, if you want here's a compile script: https://files.ari-web.xyz/files/compile_vim.sh and install these packages:
> 
> ```shell
> apt update && apt install cargo nodejs npm clang gcc ccls python3 python3-pip ruby tcl \
>         xorg-dev lua5.4 liblua5.4-dev binutils perl binutils fasm xclip curl \
>         git shfmt clang-format tmux bash-completion man-db mlocate \
>         pkgconf  -y
> ```
> 
> If a package fails to install just remove it form the liswill try 

> > > Hi person, /usr/bin/lsd is a program which just improves ls
> > > If you want to install lsd:
> > > ```shell
> > > pkg install lsd
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Or if you just want to remove the alias, remove it from `~/.config/shells/bash/bash.aliases`
> > 
> > 
> > Thanks mate, it worked
> > One more help if possible. I am getting this error "Error: Error on...quires pyx support on vim. & Server languageserver.ccls failed to start: Launching server "languageserver.ccls" using command ccls failed." while open vim. Plugins are already installed. Do I need to do anything else?
> 
> Yeah this is bc default vim binary does not support python, you have to compile vim manually, but I rarely need vim on my phone or my phone in general so idc rlly, if you want here's a compile script: https://files.ari-web.xyz/files/compile_vim.sh and install these packages:
> 
> ```shell
> apt update && apt install cargo nodejs npm clang gcc ccls python3 python3-pip ruby tcl \
>         xorg-dev lua5.4 liblua5.4-dev binutils perl binutils fasm xclip curl \
>         git shfmt clang-format tmux bash-completion man-db mlocate \
>         pkgconf  -y
> ```
> 
> If a package fails to install just remove it form the list

Will try, Thanks!
